language: erlang
otp_release:
   - 17.0 
before_install:
   - git clone https://github.com/elixir-lang/elixir
   - git checkout -b travis_branch v0.12.5
   - make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script:
   - mix deps.get
   - mix test
